### ISSUE TITLE
Search and sort options for publications

### ISSUE THREAD

**Issue by NMudunuru** [bessagroup/bessagroup#13] opened 2021-06-13 18:53 UTC
#2

**Comment by manuGil** [comment] 2021-06-24 08:59
@NMudunuru I noticed the the buttons (abstract, doi, bibtex) of the publication page do not work, at least not when the website is run locally.  Can you double check that they work for you? or maybe there are some dependencies missing in the main branch.

**Comment by NandithaMudunuru** [comment] 2021-06-24 16:33
@manuGil  could you confirm as to which branch you are on?
I'll check it.

**Comment by manuGil** [comment] 2021-06-24 16:48
> @manuGil could you confirm as to which branch you are on?
> I'll check it.

You changes were merged to the main branch. Then, that's the code I tested this morning.

**Comment by NMudunuru** [comment] 2021-07-25 16:28
Hi @manuGil,
My fork is currently synced with the main of this repo, when I run the site locally, the buttons are working on my system.
Does the problem still exist? 
If so can we schedule a meeting for this?

**Comment by manuGil** [comment] 2021-08-11 09:44
Hello @NMudunuru 
Sorry for my late reply. I wasn't in office the past weeks due to personal reasons. I am back this week and I will check if the issue is solved ASAP. Thanks for following on this!

**Closed as completed** 2021-08-19 09:19 UTC
